def chinese_to_english(chinese_input):
    # 英雄数据（格式：中文称号 - 中文名 - 英文名）
    hero_data = """
    扭曲树精 - 茂凯 - Maokai
    齐天大圣 - 孙悟空 - Wukong
    暮光之眼 - 慎 - Shen
    德邦总管 - 赵信 - XinZhao
    盲僧 - 李青 - LeeSin
    无极剑圣 - 易大师 - MasterYi
    戏命师 - 烬 - Jhin
    皎月女神 - 戴安娜 - Diana
    魔蛇之拥 - 卡西奥佩娅 - Cassiopeia
    影流之镰 - 凯隐 - Kayn
    诺克萨斯之手 - 德莱厄斯 - Darius
    黑暗元首 - 辛德拉 - Syndra
    北地之怒 - 瑟庄妮 - Sejuani
    青钢影 - 卡密尔 - Camille
    德玛西亚皇子 - 嘉文四世 - JarvanIV
    暗夜猎手 - 薇恩 - Vayne
    武器大师 - 贾克斯 - Jax
    未来守护者 - 杰斯 - Jayce
    牧魂人 - 约里克 - Yorick
    堕落天使 - 莫甘娜 - Morgana
    死亡颂唱者 - 卡尔萨斯 - Karthus
    符文法师 - 瑞兹 - Ryze
    蛮族之王 - 泰达米尔 - Tryndamere
    祖安狂人 - 蒙多 - drmundo
    远古巫灵 - 泽拉斯 - Xerath
    法外狂徒 - 格莱弗斯 - Graves
    爆破鬼才 - 吉格斯 - Ziggs
    黑暗之女 - 安妮 - Annie
    寒冰射手 - 艾希 - Ashe
    邪恶小法师 - 维嘉 - Veigar
    雪人骑士 - 努努 - Nunu
    披甲龙龟 - 拉莫斯 - Rammus
    赏金猎人 - 厄运小姐 - MissFortune
    殇之木乃伊 - 阿木木 - Amumu
    大发明家 - 黑默丁格 - Heimerdinger
    恶魔小丑 - 萨科 - Shaco
    炼金术士 - 辛吉德 - Singed
    迅捷斥候 - 提莫 - Teemo
    战争之影 - 赫卡里姆 - Hecarim
    傲之追猎者 - 雷恩加尔 - Rengar
    熔岩巨兽 - 墨菲特 - Malphite
    巨魔之王 - 特朗德尔 - Trundle
    生化魔人 - 扎克 - Zac
    卡牌大师 - 崔斯特 - TwistedFate
    机械公敌 - 兰博 - Rumble
    永猎双子 - 千珏 - Kindred
    潮汐海灵 - 菲兹 - Fizz
    英勇投弹手 - 库奇 - Corki
    末日使者 - 费德提克 - Fiddlesticks
    刀锋之影 - 泰隆 - Talon
    魂锁典狱长 - 锤石 - Thresh
    酒桶 - 古拉加斯 - Gragas
    海洋之灾 - 普朗克 - Gangplank
    正义巨像 - 加里奥 - Galio
    圣殿之毅 - 波比 - Poppy
    瘟疫之源 - 图奇 - Twitch
    祖安怒兽 - 沃里克 - Warwick
    皮城执法官 - 蔚 - Vi
    放逐之刃 - 瑞雯 - Riven
    诺克萨斯统领 - 斯维因 - Swain
    天启者 - 卡尔玛 - Karma
    逆羽 - 霞 - Xayah
    幻翎 - 洛 - Rakan
    刀锋舞者 - 艾瑞莉娅 - Irelia
    暗影之拳 - 阿卡丽 - Akali
    狂暴之心 - 凯南 - Kennen
    众星之子 - 索拉卡 - Soraka
    唤潮鲛姬 - 娜美 - Nami
    疾风剑豪 - 亚索 - Yasuo
    九尾妖狐 - 阿狸 - Ahri
    发条魔灵 - 奥莉安娜 - Orianna
    暗裔剑魔 - 亚托克斯 - Aatrox
    铸星龙王 - 奥瑞利安 - AurelionSol
    冰晶凤凰 - 艾尼维亚 - Anivia
    光辉女郎 - 拉克丝 - Lux
    圣枪游侠 - 卢锡安 - Lucian
    沙漠死神 - 内瑟斯 - Nasus
    战争女神 - 希维尔 - Sivir
    深海泰坦 - 诺提勒斯 - Nautilus
    无畏战车 - 厄加特 - Urgot
    惩戒之箭 - 维鲁斯 - Varus
    机械先驱 - 维克托 - Viktor
    仙灵女巫 - 璐璐 - Lulu
    审判天使 - 凯尔 - Kayle
    复仇焰魂 - 布兰德 - Brand
    蒸汽机器人 - 布里茨 - Blitzcrank
    迷失之牙 - 纳尔 - Gnar
    荣耀行刑官 - 德莱文 - Draven
    铁铠冥魂 - 莫德凯撒 - Mordekaiser
    弗雷尔卓德之心 - 布隆 - Braum
    诡术妖姬 - 乐芙兰 - LeBlanc
    永恒梦魇 - 魔腾 - Nocturne
    痛苦之拥 - 伊芙琳 - Evelynn
    德玛西亚之力 - 盖伦 - Garen
    时光守护者 - 基兰 - Zilean
    战争之王 - 潘森 - Pantheon
    曙光女神 - 蕾欧娜 - Leona
    牛头酋长 - 阿利斯塔 - Alistar
    时间刺客 - 艾克 - Ekko
    暴走萝莉 - 金克丝 - Jinx
    冰霜女巫 - 丽桑卓 - Lissandra
    复仇之矛 - 卡莉丝塔 - Kalista
    不祥之刃 - 卡特琳娜 - Katarina
    皮城女警 - 凯特琳 - Caitlyn
    暮光星灵 - 佐伊 - Zoe
    无双剑姬 - 菲奥娜 - Fiora
    琴瑟仙女 - 娑娜 - Sona
    野兽之灵 - 乌迪尔 - Udyr
    水晶先锋 - 斯卡纳 - Skarner
    猩红收割者 - 弗拉基米尔 - Vladimir
    探险家 - 伊泽瑞尔 - Ezreal
    亡灵战神 - 塞恩 - Sion
    风暴之怒 - 迦娜 - Janna
    岩雀 - 塔莉娅 - Taliyah
    影流之主 - 劫 - Zed
    河流之王 - 塔姆 - TahmKench
    蜘蛛女皇 - 伊莉丝 - Elise
    荆棘之兴 - 婕拉 - Zyra
    瓦洛兰之盾 - 塔里克 - Taric
    虚空先知 - 马尔扎哈 - Malzahar
    龙血武姬 - 希瓦娜 - Shyvana
    雷霆咆哮 - 沃利贝尔 - Volibear
    狂战士 - 奥拉夫 - Olaf
    山隐之焰 - 奥恩 - Ornn
    沙漠皇帝 - 阿兹尔 - Azir
    翠神 - 艾翁 - Ivern
    暴怒骑士 - 克烈 - Kled
    德玛西亚之翼 - 奎因 - Quinn
    麦林炮手 - 崔丝塔娜 - Tristana
    星界游神 - 巴德 - Bard
    海兽祭司 - 俄洛伊 - Illaoi
    虚空恐惧 - 科加斯 - ChoGath
    深渊巨口 - 克格莫 - KogMaw
    虚空之眼 - 维克兹 - VelKoz
    虚空遁地兽 - 雷克塞 - RekSai
    虚空掠夺者 - 卡兹克 - KhaZix
    虚空之女 - 卡莎 - KaiSa
    虚空行者 - 卡萨丁 - Kassadin
    荒漠屠夫 - 雷克顿 - Renekton
    狂野女猎手 - 奈德丽 - Nidalee
    """
    # 创建映射字典（同时包含中文称号和中文名）
    hero_dict = {}
    for line in hero_data.strip().split('\n'):
        parts = line.split(' - ')
        if len(parts) == 3:
            title, name, english = [part.strip() for part in parts]
            hero_dict[title] = english  # 中文称号作为键
            hero_dict[name] = english  # 中文名作为键

    return hero_dict.get(chinese_input, None)
